### ISSUE TITLE
Retrieving My booking

### ISSUE THREAD

**Issue by menschikov** [windingtree/crypto-booking#237]
@skkr this should be done via email 100%! A user wants to quickly get info about his booking, he doesn't know any hashes etc, maybe on the way and wants to check from mobile phone. He should enter just email address and get a mail with all details

**Comment by AugustoL** [comment]
This cannot be done by email because the information es encrypted and if we do it via email I would be able to get your booking information by using your personal email.
The server receives a public key (bookingHash) in his email used to view booking information and personal data (only by him), and a booking index that is used for check in in the hotel. 

@menschikov can we close this issue?

**Comment by menschikov** [comment]
We ask the user for email while booking... So we don't store the anywhere accessible just by us, the email can be de-crypted only by hash from the user? 

I see the point from the technology side and that's cool idea how to show dealing with ownership of personal data. But from the UX side and efficiency of process that's not good. We can close it because we can't do anything with it now.
