### ISSUE TITLE
Consolidate links style

### ISSUE THREAD

**Issue by martinbilek** [windingtree/crypto-booking#290]
There is "too much" different styles/colours for "links" (see below). I would suggest to have only one style for all links in application so it's easy for users to understand what is link.

I would prefer, to have only underlined blue links (underline may appear on mouse hover only).

![screen shot 2018-08-09 at 16 23 43](https://user-images.githubusercontent.com/797392/43905547-93d17ad0-9bf1-11e8-90bc-cec87b4d906b.png)
![screen shot 2018-08-09 at 16 23 51](https://user-images.githubusercontent.com/797392/43905548-93ef87e6-9bf1-11e8-8d7b-01f1aec24063.png)
![screen shot 2018-08-09 at 16 23 57](https://user-images.githubusercontent.com/797392/43905550-94333608-9bf1-11e8-9051-434e96b61c34.png)
![screen shot 2018-08-09 at 16 24 05](https://user-images.githubusercontent.com/797392/43905551-945bc10e-9bf1-11e8-8471-0513ae4970e4.png)
![screen shot 2018-08-09 at 16 24 09](https://user-images.githubusercontent.com/797392/43905552-948055d2-9bf1-11e8-8430-392e9b4e1d85.png)

**Comment by skkr** [comment]
@martinbilek yes, this needs to be revised. 

Some "not underlined" links come from the WT website (since is the base for our CSS framework), and reviewing it is a pending task. We could make them underlined in the booking app, but then would be inconsistent with our website.

The others are buttons, and less relevant links, with a different purpose, so is intentional to differentiate them, however I agree it needs to be reviewed, but in my opinion is a task to address on the WT-UI, after a previews design task and with more time.

@AugustoL @menschikov what do you think?

**Comment by AugustoL** [comment]
@skkr agree
